var LCSKChat=function(){var requestChat=false;var pingCount=0;var pingIntervalId;var chatId='';var lastMsgId=0;var chatStatus='offline';var chatEditing=false;sessionStorage["from"]="";var options=[];function setDefaults(){options.position='fixed';options.opId='';options.placement='bottom-right';options.from=sessionStorage["from"];options.headerPaddings='4px 10px 4px 10px';options.headerBackgroundColor='#970904';options.headerTextColor='white';options.headerBorderColor='#C00000';options.headerGradientStart='#970904';options.headerGradientEnd='#C00000';options.headerFontSize='small';options.boxBorderColor='#BF0000';options.boxBackgroundColor='white';options.width=350;options.offlineTitle='Chat Offline. Clique para enviar um e-mail.';options.onlineTitle='Fale conosco! Estamos Online!';options.waitingForOperator='Obrigado, sÃ³ 1min atÃ© entrarmos no chat...';options.emailSent='Seu e-mail foi enviado, obrigado. Entraremos em contato em breve.';options.emailFailed='Ops! O email nÃ£o pode ser enviado no momento.<br /><br />Desculpe.';}
function checkStatus(){if(document.location.href.toLowerCase().indexOf('/chat/go/')>-1){window.setTimeout(function(){document.location.href=document.location.href.replace('$status','');},12345);}}
function config(args){checkStatus()
setDefaults();if(args!=null){for(key in options){if(args[key]){options[key]=args[key];}}}}
function getPlacement(){if(options.placement=='bottom-right'){return'bottom:0px;right:0px;';}
return'';}
function init(){$('body').append('<div id="chat-box-header" style="display: block; z-index:1000; position:'+options.position+';'+getPlacement()+'width:'+options.width+'px;padding:'+options.headerPaddings+';color:'+options.headerTextColor+';font-size:'+options.headerFontSize+';cursor:pointer;background:'+options.headerBackgroundColor+';filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=\''+options.headerGradientStart+'\', endColorstr=\''+options.headerGradientEnd+'\');background: -webkit-gradient(linear, left top, left bottom, from('+options.headerGradientStart+'), to('+options.headerGradientEnd+'));background: -moz-linear-gradient(top,  '+options.headerGradientStart+',  '+options.headerGradientEnd+');border:2px solid '+options.headerBorderColor+';border-radius: 5px;">'+options.offlineTitle+'</div>'+'<div id="chat-box" style="display:none; z-index:1000; position:'+options.position+';'+getPlacement()+'width:'+options.width+'px;height:300px;padding: 10px 10px 10px 10px;border: 1px solid '+options.boxBorderColor+';background-color:'+options.boxBackgroundColor+';font-size:small;"></div>');pingIntervalId=window.setInterval(function(){if(pingCount>=3){pingCount=0;$.ajax({type:'GET',dataType:'jsonp',async:false,url:'http://www.ipara.com.br/veiculo/Chat/Ping',crossDomain:true,data:({page:document.location.href,opId:options.opId}),success:function(data){if(data.visitorping=='failed'){clearInterval(pingIntervalId);$('#chat-box-header').hide();$('#chat-box').hide();}
else
if(data.visitorping!=chatStatus)
{if(data.visitorping!=chatId){var state=false;if(data.visitorping!='online'&&data.visitorping!='offline')
{chatId=data.visitorping;state=true;}
else
{state=data.visitorping=='online';}
chatStatus=state?'online':'offline';chatRefreshState(state);}}}});}
else{pingCount++;}
getMsgs();},1000);logVisit();$('#chat-box-header').click(function(){toggleChatBox();});$('#chat-box-sendname').live({click:function(event){event.preventDefault();sessionStorage["from"]=$("#chat-box-name").val();$("#boxnome").hide();$("#boxmsg, #chat-box-input").show();}});$('#chat-box').on({keydown:function(e){var msg=$(this).val();if(e.keyCode==13){if(chatId==null||chatId==''){$.ajax({type:'GET',dataType:'jsonp',url:'http://www.ipara.com.br/veiculo/chat/requestchat',crossDomain:true,data:({opId:options.opId}),success:function(data){if(data.status){requestChat=true;chatId=data.chatId;lastChatStatus=chatId;$('#chat-box-msg').html(options.waitingForOperator);$.ajax({type:'GET',dataType:'jsonp',url:'http://www.ipara.com.br/veiculo/chat/addmsg',crossDomain:true,data:{id:chatId,from:sessionStorage["from"],msg:msg},success:function(data){$('#chat-box-textinput').val('');getMsgs();}});}}});}
else{$.ajax({type:'GET',dataType:'jsonp',url:'http://www.ipara.com.br/veiculo/chat/addmsg',crossDomain:true,data:({id:chatId,from:sessionStorage["from"],msg:msg}),success:function(data){$('#chat-box-textinput').val('');getMsgs();}});}}}},'#chat-box-textinput');$('#chat-box').on({keydown:function(){chatEditing=true;}},'.chat-editing');$('#chat-box').on({click:function(){$('#chat-box').html(options.emailSent);$.ajax({type:'GET',dataType:'jsonp',url:'http://www.ipara.com.br/veiculo/chat/sendemail',crossDomain:true,data:({email:$('#chat-box-email').val(),comment:$('#chat-box-cmt').val()}),success:function(data){if(data.mailsent=='ok'){chatEditing=false;}else{$('#chat-box').html(options.emailFailed);}}});}},'#chat-box-send');setAjaxErrorAction();}
function setAjaxErrorAction(){$(document).ajaxError(function(event,jqXHR,ajaxSettings,thrownError){alert('[event:'+event+'], [jqXHR:'+jqXHR+'], [ajaxSettings:'+ajaxSettings+'], [thrownError:'+thrownError+'])');});}
function logVisit(){$.ajax({type:'GET',dataType:'jsonp',url:'http://www.ipara.com.br/veiculo/chat/logvisit',crossDomain:true,data:({page:document.location.href,referrer:document.referrer,opId:options.opId}),success:function(data){lastChatStatus=data;if(data.logvisit=='failed'){$('#chat-box-header').hide();$('#chat-box').hide();}else{var state=false;if(data.logvisit!='online'&&data.logvisit!='offline'){chatId=data.logvisit;state=true;}else{state=data.logvisit=='online';}
chatStatus=state?'online':'offline';chatRefreshState(state);}}});}
function chatRefreshState(state){if(state)
{$('#chat-box-header').text(options.onlineTitle);if(!requestChat){$('#chat-box').html('<div id="chat-box-msg" style="height:265px;overflow:auto;">'+'<br/><div id="boxnome">'+'<p>Alguma dÃºvida? Converse conosco!</p>'+'<p>Seu nome</p><input type= "text" id="chat-box-name" size="20"  class="tbstyle" />'+'<br/><input type="button" class="css3button " id="chat-box-sendname" value="Entrar no chat" ></div>'+'<div id="boxmsg" style="display:none">'+'<p>Digite sua mensagem no campo abaixo e tecle ENTER.</p></div></div>'+'<div id="chat-box-input" style="height:35px; display:none"><textarea id="chat-box-textinput" style="width:200px;height: 20px;" class="tbstyle" /></div>');}else{}}else{$('#chat-box-header').text(options.offlineTitle);$('#chat-box-input').hide();$('#chat-box').html('<p>Seu e-mail</p><input type="text" id="chat-box-email";width: 100%;" class="chat-editing tbstyle" />'+'<p>Sua mensagem</p><textarea id="chat-box-cmt" cols="40" rows="7" class="chat-editing tbstyle" ></textarea>'+'<br/><input type="button" class="css3button " id="chat-box-send" value="Envie uma mensagem." />');}}
function getMsgs(){if(chatId!=null&&chatId!=''){if(!requestChat){if(!$('#chat-box').hasClass('chat-open')){toggleChatBox();}
requestChat=true;}
$.ajax({type:'GET',dataType:'jsonp',url:'http://www.ipara.com.br/veiculo/chat/pollmsgs',crossDomain:true,data:({id:chatId,lastId:lastMsgId}),success:function(data){if(data.lastId>lastMsgId){lastMsgId=data.lastId;for(i=0;i<data.msgs.length;i++){$('#chat-box-msg').append('<p><strong>'+data.msgs[i].FromName+'</strong>: '+data.msgs[i].Message+'</p>');if(data.msgs[i].FromName=='system'){chatId='';chatStatus='';requestChat=false;}}
$("#chat-box-msg").scrollTop($("#chat-box-msg")[0].scrollHeight);}}});}}
function toggleChatBox(){var elm=$('#chat-box-header');if($('#chat-box').hasClass('chat-open')){$('#chat-box').removeClass('chat-open');elm.css('bottom','0px');}else{var y=308+elm.height();$('#chat-box').addClass('chat-open');elm.css('bottom',y);}
$('#chat-box').slideToggle();}
return{config:config,init:init}}();